### ISSUE TITLE
运行代码出现了点问题

### ISSUE THREAD

**Issue by yeyoupi** [cueavyqwp/tfc-forge-tool#1]
发生异常: TypeError
lang.__init__() got an unexpected keyword argument 'lang_dir'
  File "E:\zuomian\1\tfc-forge-tool-main\tfc_anvil.py", line 23, in <module>
    lang = langful.lang( lang_dir = os.path.join( os.path.split( __file__ )[ 0 ] , "lang" ) )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: lang.__init__() got an unexpected keyword argument 'lang_dir'

**Comment by cueavyqwp** [comment]
这是个BUG,已经修复
重新下载代码再尝试运行
