### ISSUE TITLE
2个末尾要求无法获得完美

### ISSUE THREAD

**Issue by guoyaoyao2011** [cueavyqwp/tfc-forge-tool#2]
如下图，有时只有2个末尾要求，而软件并没有一个无的选项，请问能否添加一下谢谢
![image](https://github.com/user-attachments/assets/a69d5db2-a480-46fb-8e73-a1ae139d2f8b)

**Comment by cueavyqwp** [comment]
现在添加了一个新选项`任意`,会选择输出最优解

![屏幕截图 2024-08-13 183408](https://github.com/user-attachments/assets/8e491ab8-82c5-4730-b2c7-f6a0dcf3b3e8)

更新代码然后试试

**Comment by guoyaoyao2011** [comment]
谢谢，已经解决了
